/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 beer-model/beer-model-1-compressed.gltf --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'animation_0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['0']: THREE.Mesh
    Ipa: THREE.Mesh
    Blond: THREE.Mesh
    Stout: THREE.Mesh
    Neipa: THREE.Mesh
  }
  materials: {
    ['Mat.1']: THREE.MeshStandardMaterial
    Ipa: THREE.MeshStandardMaterial
    Blond: THREE.MeshStandardMaterial
    Stout: THREE.MeshStandardMaterial
    Neipa: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/beer-model-1-compressed.gltf') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="groep_brewdistrict_blikjes" position={[-0.15, 0.891, 0.013]} rotation={[-1.29, -0.92, -1.297]}>
          <mesh name="0" geometry={nodes['0'].geometry} material={materials['Mat.1']} position={[0.013, 0.027, 0.021]} rotation={[1.568, 0, 0]} />
          <mesh name="Ipa" geometry={nodes.Ipa.geometry} material={materials.Ipa} position={[0.013, 0.027, 0.021]} rotation={[1.568, 0, 0]} />
          <mesh name="Blond" geometry={nodes.Blond.geometry} material={materials.Blond} position={[0.013, 0.027, 0.021]} rotation={[1.568, 0, 0]} />
          <mesh name="Stout" geometry={nodes.Stout.geometry} material={materials.Stout} position={[0.013, 0.027, 0.021]} rotation={[1.568, 0, 0]} />
          <mesh name="Neipa" geometry={nodes.Neipa.geometry} material={materials.Neipa} position={[0.013, 0.027, 0.021]} rotation={[1.568, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/beer-model-1-compressed.gltf')
