import Cup from "../../components/svg/Cup";
import Cart from "../../components/svg/Cart";

export const locations = [
  {
    name: "Proeflokaal Van Horst",
    location: "Horst",
    icon: Cup,
  },
  {
    name: "Onze Bierwinkel",
    location: "Nijmegen",
    icon: Cart,
  },
  {
    name: "Tierney's Irish Pubs",
    location: "Nijmegen",
    icon: Cup,
  },
  {
    name: "Nico De Witt Plus",
    location: "Beek",
    icon: Cart,
  },
  {
    name: "Grut Eten & Drinken",
    location: "Nijmegen",
    icon: Cup,
  },
  {
    name: "Cafe Samson",
    location: "Nijmegen",
    icon: Cup,
  },
  {
    name: "Cafe De Deut",
    location: "Nijmegen",
    icon: Cup,
  },
  { name: "De Mariaschool", location: "Nijmegen", icon: Cup },
];

export const imageSequence = [
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0001.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0002.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0003.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0004.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0005.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0006.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0007.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0008.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0009.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0010.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0011.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0012.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0013.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0014.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0015.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0016.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0017.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0018.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0019.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0020.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0021.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0022.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0023.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0024.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0025.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0026.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0027.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0028.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0029.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0030.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0031.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0032.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0033.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0034.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0035.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0036.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0037.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0038.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0039.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0040.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0041.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0042.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0043.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0044.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0045.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0046.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0047.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0048.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0049.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0050.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0051.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0052.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0053.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0054.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0055.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0056.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0057.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0058.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0059.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0060.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0061.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0062.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0063.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0064.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0065.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0066.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0067.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0068.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0069.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0070.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0071.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0072.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0073.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0074.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0075.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0076.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0077.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0078.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0079.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0080.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0081.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0082.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0083.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0084.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0085.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0086.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0087.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0088.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0089.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0090.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0091.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0092.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0093.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0094.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0095.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0096.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0097.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0098.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0099.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0100.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0101.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0102.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0103.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0104.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0105.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0106.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0107.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0108.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0109.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0110.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0111.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0112.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0113.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0114.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0115.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0116.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0117.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0118.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0119.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0120.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0121.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0122.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0123.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0124.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0125.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0126.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0127.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0128.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0129.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0130.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0131.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0132.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0133.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0134.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0135.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0136.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0137.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0138.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0139.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0140.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0141.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0142.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0143.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0144.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0145.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0146.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0147.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0148.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0149.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0150.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0151.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0152.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0153.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0154.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0155.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0156.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0157.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0158.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0159.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0160.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0161.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0162.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0163.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0164.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0165.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0166.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0167.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0168.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0169.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0170.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0171.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0172.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0173.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0174.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0175.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0176.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0177.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0178.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0179.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0180.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0181.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0182.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0183.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0184.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0185.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0186.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0187.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0188.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0189.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0190.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0191.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0192.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0193.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0194.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0195.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0196.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0197.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0198.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0199.jpg",
  "https://brewdistrict24.com/gfx/sequence%20images/cans-v3/brewdistrict_scroll_blikjes0200.jpg",
];
